language: php
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: TODO
branches:
  only:
  - dev
  - "/\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
php:
- 7.1
- 7.2
- nightly
env:
- WP_VERSION=latest WP_MULTISITE=1 TRAVIS_NODE_VERSION="6"
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
before_install:
- source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
install:
- node -v
- npm install -g yarn
- yarn
- composer install
before_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]] && php -v | grep -q 'Xdebug'; then phpenv config-rm xdebug.ini; fi
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- git clone --depth=1 https://github.com/pressbooks/pressbooks.git ../pressbooks
- cd ../pressbooks && composer install --no-dev
- cd ../pressbooks-cas-sso
script:
- yarn run lint
- yarn run build:production
- vendor/bin/phpunit --configuration phpunit.xml --coverage-clover coverage.xml
- vendor/bin/phpcs --standard=phpcs.ruleset.xml *.php inc/ bin/
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- export TRAVIS_PROJECT_SLUG="$(basename $TRAVIS_BUILD_DIR)"
- composer install --no-dev --optimize-autoloader
- cd ../
- zip -9 -ry $TRAVIS_BUILD_DIR/$TRAVIS_PROJECT_SLUG-$TRAVIS_TAG.zip $TRAVIS_PROJECT_SLUG
  -x *.git* *assets/src/\* *bin/\* *node_modules/\* *tests/\* *.editorconfig* *.gitattributes*
  *.github* *.gitignore* *.phpstorm.meta.php* *.travis.yml* *.tx/\* *Gruntfile.js*
  *package-lock.json* *phpcs.ruleset.xml* *phpunit.xml* *webpack.mix.js* *yarn.lock*
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: UfrnmbTZUfp4nPSa81uuw6RYeXLq1Ncr9FMG9zR+a5B+sg7d8/lRlg8yE4GSL1vUO62+egrQvkUtxGq7z+0uImox7sbX+y6iuO/ZK1JpXrrU+aFQdMxC5U+hqr4ZfqnHXXLlNNM7451IWQ+WUjJCKSnaxQ5WhHy0EFoGECSIpNgfXxiS1P9mGzLhbscyccCvSMWhj9eDW2CmWrWIelGo3h4mqlFZb4mqJhwLCe/Q/n6lp20hGPr/vDbRCpi9e6kr4InP9uByCGfSYye+a/hQqMXsLxXvN7taronCZXcGxF9Dr+h5cEGWaP1+L/VXmzEIutniM+1Ti85AZ9wwYNBuYwvLYJ8Nb+IOK6Y3zwYRKzpLFynL3e/xeFW3Ip5WkCmcLPipwmjK0VBoZH9Bg5fWJhuiizeuAL3lBzGqrSF0xSUpNbO4gKW1negXYO2nyQu5YcfCo2Sg2D3RfY8t8xy7NlWWtGsHnsO3DJZJTtTWOR+v4e5puUJcsFhgMTAN9wGYHra0ehar7YJ7/TATf2ejzWPh1A+/1L7dKJITXj9SaGjIeMjF08ssQEf4rtatJZ5A7ivMLRBWQ7ofEHkfMnbQIQs8LaV/LHimioX5bEsQnJ4mWrMIMi8Q+Yaeaxk1A29MBihOGGUTOqPc9xNSynXo7QbTyxkg39nLkJBxnYzPJlo=
  file: "pressbooks-cas-sso-$TRAVIS_TAG.zip"
  on:
    tags: true
    repo: pressbooks/pressbooks-cas-sso
